# this is just a config file for gitpod. Try it out at https://gitpod.io/#https://github.com/temporalio/samples-typescript/
ports:
  - port: 5432
  - port: 7233
  - port: 8088
  - port: 9200
tasks:
  - name: Run Hello World Worker
    init: |
      cd hello-world
      gp open README.md
      npm install
      gp sync-done install-done
    command: |
      gp sync-await server-up
      npm run start.watch
  - name: Run Hello World Workflow
    command: |
      cd hello-world
      gp sync-await install-done
      gp sync-done server-up
      npm run workflow
      gp preview http://localhost:8088 # reload Temporal Web to show new workflow
#      until docker exec temporal-admin-tools tctl cl h; do sleep 2; done; clear; # retry until it works
    openMode: split-right
#  - name: Temporal Server
#    command: docker-compose up
  - name: Temporalite 
    init: go install github.com/DataDog/temporalite/cmd/temporalite@latest
    command: temporalite start
  - name: Temporal Web/tctl
#      gp await-port 8088 # temporal web
    command: |
      docker run -t -i -p 8088:8088 -e TEMPORAL_GRPC_ENDPOINT=7233
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v" # can't run tctl directly from gitpod.yml
    openMode: split-right
