# this is just a config file for gitpod. Try it out at https://gitpod.io/#https://github.com/temporalio/samples-typescript/
ports:
  - port: 5432
  - port: 7233
  - port: 8088
  - port: 9200
tasks:
  - name: Run Hello World Worker
    init: |
      cd hello-world
      gp open README.md
      npm install
    command: |
      gp sync-await server-up
      npm run start.watch
  - name: Run Hello World Workflow
    command: |
      cd hello-world
      gp sync-await server-up
      npm run workflow
    openMode: split-right
  - name: Temporal Server
    command: docker-compose up
  - name: Temporal Web/tctl
    command: |
      gp await-port 8088
      gp preview http://localhost:8088
      alias tctl="docker exec temporal-admin-tools tctl"
      tctl -v
      gp sync-done server-up
    openMode: split-right
